import { app, BrowserWindow, desktopCapturer, ipcMain, screen } from "electron";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    frame: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.webContents.openDevTools();
};

app.whenReady().then(() => {
  createWindow();
  mainWindow.hide()
  ipcMain.handle("startStream", startStream);
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }

  if (!mainWindow.isVisible()) {
    mainWindow.show();
  }
});





const getMonitorInFocus = async () => {
  const cursorPosition = screen.getCursorScreenPoint();
  const currentMonitor = screen.getDisplayNearestPoint(cursorPosition);

  const sources = await desktopCapturer.getSources({ types: ["screen"] });
  const activeSource = sources.find(
    (source) => source.display_id === currentMonitor.id.toString(),
  );

  if (activeSource === undefined) {
    console.error(
      "Unable to find source with id: " + currentMonitor.id.toString(),
    );
    return;
  }
  return activeSource.id;
};

let lastMonitorId = "";
const streamCron = async () => {
  const srcID = await getMonitorInFocus();
  if (srcID !== lastMonitorId) {
    lastMonitorId = srcID;
    mainWindow.webContents.send("updateStreamSource", srcID);
  }
};

let streamMonitor: NodeJS.Timeout
const startStream = async () => {
  const srcID = await getMonitorInFocus();

  if(streamMonitor === undefined){
    streamMonitor = setInterval(streamCron, 100);
    lastMonitorId = srcID;
  }

  return srcID
}
